### ISSUE TITLE
Support for arbitrary-size integers?

### ISSUE THREAD

**Issue by kapitaali** [japhb/CBOR-Simple#3]
Hi,

I tried signing a message with a key (in Raku REPL):
```
> use CBOR::Simple; my $tagged = CBOR::Simple::Tagged.new( tag-number => 0xa20126044875997941cd2d9b21.Int, value => "hello sir" ); my $comp = cbor-encode($tagged); say $comp;

Cannot unbox 104 bit wide bigint into native integer
  in sub cbor-encode at /home/theb/.rakubrew/versions/moar-2021.10/install/share/perl6/site/sources/983E0FAFB758220B170D33A30493A316F0805F75 (CBOR::Simple) line 151
  in sub cbor-encode at /home/theb/.rakubrew/versions/moar-2021.10/install/share/perl6/site/sources/983E0FAFB758220B170D33A30493A316F0805F75 (CBOR::Simple) line 141
  in block <unit> at <unknown file> line 1
```

How hard would it be to shift from bigint native to Int class?

**Comment by japhb** [comment]
OK, before I address the actual failure, one really important bit first:

**CBOR tags are not signatures and are not security-related!**

They are generally used to indicate type within the [CBOR Tags IANA registry](https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml) .  For example, I registered the [Capture](https://github.com/japhb/cbor-specs/blob/main/capture.md) type, which is assigned tag number 25441.

The problem you are running into is that (given that they are just used to look up types in the registry), CBOR tag numbers are only defined for the range of `uint64` (0 to 2^64 - 1).  It makes no sense to support larger tag numbers, because they cannot be encoded.  (Mind you, a low-numbered tag *could* be defined with the express intent of *describing* a big integer tag number, but I'm not aware of anyone wanting to do that yet, especially since big chunks of the tag number range are reserved for local use anyway.)

But since you're talking about signing and keys, perhaps you were looking instead for [COSE (CBOR Object Signing and Encryption)](https://datatracker.ietf.org/doc/html/rfc8152) or perhaps [CWT (CBOR Web Token)](https://datatracker.ietf.org/doc/html/rfc8392) which is based on COSE?  I haven't created a module for either of those yet, though they'd be useful additions to the ecosystem for sure.  :slightly_smiling_face:

**Comment by kapitaali** [comment]
Yeah, you have interpreted my question exactly as I intended. I'll wait for the CBOR signing functionality.
